kind: Deployment
apiVersion: apps/v1
metadata:
  name: runregistry-frontend
  # TODO: Update namespace
  namespace: birdup
  labels:
    app: runregistry-frontend
    app.kubernetes.io/component: runregistry-frontend
    app.kubernetes.io/instance: runregistry-frontend
    app.kubernetes.io/name: runregistry-frontend
    app.kubernetes.io/part-of: runregistry
    # TODO: Update namespace
    app.openshift.io/runtime-namespace: birdup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runregistry-frontend
  template:
    metadata:
      labels:
        app: runregistry-frontend
        deployment: runregistry-frontend
    spec:
      containers:
        - name: runregistry-frontend
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 1024Mi
          command:
            - npm
            - start
          envFrom:
            - secretRef:
                name: runregistry-frontend-secret
          imagePullPolicy: Always
          # TODO: Update namespace
          image: >-
            image-registry.openshift-image-registry.svc:5000/birdup/runregistry-frontend:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
