kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: cmsrunregistry
  labels:
    app: nginx
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: nginx
  template:
    metadata:
      labels:
        deployment: nginx
    spec:
      volumes:
        - name: nginx-default-d
          configMap:
            name: nginx
            defaultMode: 420
      containers:
        - resources:
            limits:
              cpu: "1"
              memory: 150Mi
            requests:
              cpu: 20m
              memory: 30Mi
          terminationMessagePath: /dev/termination-log
          name: nginx
          command:
            - /usr/libexec/s2i/run
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nginx-default-d
              mountPath: /opt/app-root/etc/nginx.default.d
          terminationMessagePolicy: File
          image: "image-registry.openshift-image-registry.svc:5000/openshift/nginx@sha256:77076b4757a344ccc3d133de9c44d7d2af0935e19d4e9cefbd1b42815d08df84"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 6
  replicas: 1
  updatedReplicas: 1
  unavailableReplicas: 1
