apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: runregistry-backend
  namespace: dev-cmsrunregistry
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
        openshift.io/imported-from: registry.cern.ch/cms-dqmdc/runregistry-backend
      from:
        kind: DockerImage
        name: registry.cern.ch/cms-dqmdc/runregistry-backend
      referencePolicy:
        type: Local

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: runregistry-frontend
  namespace: dev-cmsrunregistry
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
        openshift.io/imported-from: registry.cern.ch/cms-dqmdc/runregistry-frontend
      from:
        kind: DockerImage
        name: registry.cern.ch/cms-dqmdc/runregistry-frontend
      referencePolicy:
        type: Local
